spring.application.name=raporlama
# Sunucu Portu
server.port=8080

# PostgreSQL Bağlantı Bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/raporlama_db?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=CEng22.d
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always